
export enum InterviewState {
  NOT_STARTED = 'NOT_STARTED',
  GENERATING_QUESTIONS = 'GENERATING_QUESTIONS',
  ASKING_QUESTION = 'ASKING_QUESTION',
  AWAITING_ANSWER = 'AWAITING_ANSWER',
  EVALUATING_ANSWER = 'EVALUATING_ANSWER',
  SHOWING_FEEDBACK = 'SHOWING_FEEDBACK',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
}
